# Generated by Django 6.0.6 on 2026-06-25 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WajibPajak',
            fields=[
                ('npwp', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('jenis', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tb_wajib_pajak',
            },
        ),
        migrations.CreateModel(
            name='SPTTahunan',
            fields=[
                ('no_lapor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tahun', models.CharField(max_length=4)),
                ('bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('terutang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(max_length=15)),
                ('tgl_lapor', models.DateTimeField(default=django.utils.timezone.now)),
                ('npwp', models.ForeignKey(db_column='npwp', on_delete=django.db.models.deletion.CASCADE, to='pajak_app.wajibpajak')),
            ],
            options={
                'db_table': 'tb_spt_tahunan',
            },
        ),
    ]
