# Generated by Django 6.0.6 on 2026-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pajak_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spttahunan',
            name='kredit_pajak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
